### ISSUE TITLE
Add filter_blocked_content method in comment and thread apis

### ISSUE THREAD

**Issue by taimoor-ahmed-1** [edly-io/forum#72]

**Comment by Faraz32123** [comment]
**filter_blocked_content Method**
- We are not migrating `filter_blocked_content` method from Ruby to Python.
- Functionality: This method was being used in threads and comments APIs. It was filtering the body (content) of the post or comment based on some blocked_hashes already stored in the mongo db and returning 503 if the body (content) matched with the blocked_hashes.
- **Reason for not migrating this method to forum V2**: There's no clue or way of adding blocked hashes in the Forum v1 current implementation, i.e., in the current discussion forum. Thus, the body (content) of a comment or thread could not be matched and blocked. As a result we are skipping this functionality.

**Comment by Faraz32123** [comment]
- We are not migrating `filter_blocked_content` method from Ruby to Python.
- **Functionality**: This method was being used in threads and comments APIs. It was filtering the body (content) of the thread or comment based on some `blocked_hashes` already stored in the mongo db and returning 503 if the body (content) matched with the blocked_hashes.
- **Reason for not migrating this method to forum V2:** There's no clue or way of adding blocked hashes in the Forum v1 current implementation, i.e., in the current discussion forum. Thus, the body (content) of a comment or thread could not be matched and blocked. As a result we are skipping this functionality. Closing this issue as it won't fix.

hello @regisb and @ormsbee, Hope you guys are doing great. I am mentioning you guys for the context of this issue.

**Comment by regisb** [comment]
For the record, all non-backward compatible decisions are documented here: https://github.com/edly-io/forum/blob/master/docs/decisions/0002-forum_v1_migration_to_v2.rst ([including this one](https://github.com/edly-io/forum/blob/master/docs/decisions/0002-forum_v1_migration_to_v2.rst#5-filter_blocked_content-method))

**Comment by ormsbee** [comment]
Thank you for the heads up. FWIW, please add more context where possible. For example, all of these are likely to take some form of "the current API doesn't actually use this", *and that's fine*. But it would help to document what these things were and why they're no longer being used. For instance, the notifications stuff in the v1 API is being stripped out–saying what used to call it (the ruby notifier that used to run as a separate process?), and where notifications live now would help–particularly since this is likely to be the only place where such things would be documented.

Likewise for the `/:commentable_id/threads` endpoints being removed. If this is because we're moving away from the early decision to make these arbitrarily nestable and we're freezing in the Post -> Reply -> Comment hierarchy (or whatever the precise terminology is), the ADR should document that change in design intent.
